from __future__ import annotations

from typing import Dict

from modules.elite_score_engine.core.types import (
    ScoringDimension,
    DimensionWeight,
    SectorType,
    ScoreDirection,
)


SECTOR_MULTIPLIERS: Dict[SectorType, Dict[ScoringDimension, float]] = {
    SectorType.BANKS: {
        ScoringDimension.FINANCIAL_QUALITY: 1.4,
        ScoringDimension.VALUATION: 1.2,
        ScoringDimension.GROWTH: 1.0,
        ScoringDimension.PROFITABILITY: 1.3,
        ScoringDimension.TECHNICAL_STRUCTURE: 0.9,
        ScoringDimension.TREND_QUALITY: 0.9,
        ScoringDimension.MOMENTUM: 0.8,
        ScoringDimension.VOLUME: 0.9,
        ScoringDimension.LIQUIDITY: 1.1,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 0.8,
        ScoringDimension.RISK: 1.2,
        ScoringDimension.SECTOR_STRENGTH: 1.3,
        ScoringDimension.MARKET_REGIME: 1.1,
        ScoringDimension.TIMING: 0.8,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.HOLDINGS: {
        ScoringDimension.FINANCIAL_QUALITY: 1.3,
        ScoringDimension.VALUATION: 1.1,
        ScoringDimension.GROWTH: 0.9,
        ScoringDimension.PROFITABILITY: 1.2,
        ScoringDimension.TECHNICAL_STRUCTURE: 0.8,
        ScoringDimension.TREND_QUALITY: 0.9,
        ScoringDimension.MOMENTUM: 0.8,
        ScoringDimension.VOLUME: 0.9,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.1,
        ScoringDimension.PATTERN_QUALITY: 0.8,
        ScoringDimension.RISK: 1.1,
        ScoringDimension.SECTOR_STRENGTH: 1.2,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 0.8,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.INDUSTRIALS: {
        ScoringDimension.FINANCIAL_QUALITY: 1.1,
        ScoringDimension.VALUATION: 1.0,
        ScoringDimension.GROWTH: 1.2,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.0,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 0.9,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 0.9,
        ScoringDimension.SECTOR_STRENGTH: 1.0,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.TECHNOLOGY: {
        ScoringDimension.FINANCIAL_QUALITY: 0.8,
        ScoringDimension.VALUATION: 0.9,
        ScoringDimension.GROWTH: 1.4,
        ScoringDimension.PROFITABILITY: 0.9,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.1,
        ScoringDimension.TREND_QUALITY: 1.1,
        ScoringDimension.MOMENTUM: 1.3,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 0.9,
        ScoringDimension.SMART_MONEY: 1.1,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 0.8,
        ScoringDimension.SECTOR_STRENGTH: 1.1,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.1,
        ScoringDimension.HISTORICAL_SIMILARITY: 0.9,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.ENERGY: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.1,
        ScoringDimension.GROWTH: 1.1,
        ScoringDimension.PROFITABILITY: 1.1,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.1,
        ScoringDimension.VOLUME: 1.1,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 0.9,
        ScoringDimension.RISK: 1.0,
        ScoringDimension.SECTOR_STRENGTH: 1.2,
        ScoringDimension.MARKET_REGIME: 1.1,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.RETAIL: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.1,
        ScoringDimension.GROWTH: 1.2,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.1,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 0.9,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 0.9,
        ScoringDimension.SECTOR_STRENGTH: 1.0,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.TRANSPORTATION: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.0,
        ScoringDimension.GROWTH: 1.1,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.0,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 0.9,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 0.9,
        ScoringDimension.SECTOR_STRENGTH: 1.0,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.CONSTRUCTION: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.1,
        ScoringDimension.GROWTH: 1.1,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.1,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 0.9,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 0.9,
        ScoringDimension.SECTOR_STRENGTH: 1.0,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.INSURANCE: {
        ScoringDimension.FINANCIAL_QUALITY: 1.3,
        ScoringDimension.VALUATION: 1.1,
        ScoringDimension.GROWTH: 1.0,
        ScoringDimension.PROFITABILITY: 1.2,
        ScoringDimension.TECHNICAL_STRUCTURE: 0.9,
        ScoringDimension.TREND_QUALITY: 0.9,
        ScoringDimension.MOMENTUM: 0.8,
        ScoringDimension.VOLUME: 0.9,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 0.8,
        ScoringDimension.RISK: 1.2,
        ScoringDimension.SECTOR_STRENGTH: 1.1,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 0.8,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.REAL_ESTATE: {
        ScoringDimension.FINANCIAL_QUALITY: 1.1,
        ScoringDimension.VALUATION: 1.2,
        ScoringDimension.GROWTH: 1.0,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 0.9,
        ScoringDimension.TREND_QUALITY: 0.9,
        ScoringDimension.MOMENTUM: 0.9,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 0.9,
        ScoringDimension.RISK: 1.1,
        ScoringDimension.SECTOR_STRENGTH: 1.1,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 0.9,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.MINING: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.0,
        ScoringDimension.GROWTH: 1.1,
        ScoringDimension.PROFITABILITY: 1.1,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.1,
        ScoringDimension.VOLUME: 1.1,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 0.9,
        ScoringDimension.RISK: 1.0,
        ScoringDimension.SECTOR_STRENGTH: 1.1,
        ScoringDimension.MARKET_REGIME: 1.1,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
    SectorType.OTHER: {
        ScoringDimension.FINANCIAL_QUALITY: 1.0,
        ScoringDimension.VALUATION: 1.0,
        ScoringDimension.GROWTH: 1.0,
        ScoringDimension.PROFITABILITY: 1.0,
        ScoringDimension.TECHNICAL_STRUCTURE: 1.0,
        ScoringDimension.TREND_QUALITY: 1.0,
        ScoringDimension.MOMENTUM: 1.0,
        ScoringDimension.VOLUME: 1.0,
        ScoringDimension.LIQUIDITY: 1.0,
        ScoringDimension.SMART_MONEY: 1.0,
        ScoringDimension.PATTERN_QUALITY: 1.0,
        ScoringDimension.RISK: 1.0,
        ScoringDimension.SECTOR_STRENGTH: 1.0,
        ScoringDimension.MARKET_REGIME: 1.0,
        ScoringDimension.TIMING: 1.0,
        ScoringDimension.HISTORICAL_SIMILARITY: 1.0,
        ScoringDimension.CONFIDENCE: 1.0,
    },
}


def apply_sector_adjustments(
    dimensions: Dict[ScoringDimension, DimensionWeight],
    sector: SectorType,
) -> Dict[ScoringDimension, DimensionWeight]:
    multipliers = SECTOR_MULTIPLIERS.get(sector, SECTOR_MULTIPLIERS[SectorType.OTHER])
    adjusted: Dict[ScoringDimension, DimensionWeight] = {}
    for dim, dw in dimensions.items():
        multiplier = multipliers.get(dim, 1.0)
        new_weight = max(0.01, min(0.30, dw.weight * multiplier))
        adjusted[dim] = DimensionWeight(
            dimension=dw.dimension,
            weight=new_weight,
            direction=dw.direction,
            min_value=dw.min_value,
            max_value=dw.max_value,
            description=dw.description,
        )
    return adjusted


def get_sector_multiplier(sector: SectorType, dim: ScoringDimension) -> float:
    multipliers = SECTOR_MULTIPLIERS.get(sector, {})
    return multipliers.get(dim, 1.0)
