import { BistSymbolEntry, BIST_EXCHANGE } from './symbol-registry.types';

const is = (ticker: string) => `${ticker}.IS`;

export const BIST_SYMBOLS: BistSymbolEntry[] = [
  {
    canonicalTicker: 'AKBNK',
    companyName: 'Akbank',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAAKBNK91N4',
    active: true,
    providers: {
      yahoo: is('AKBNK'),
      fintables: 'AKBNK',
      kap: 'AKBNK',
      tcmb: 'AKBNK',
      mkk: 'AKBNK',
    },
  },
  {
    canonicalTicker: 'GARAN',
    companyName: 'Türkiye İş Bankası C',
    exchange: BIST_EXCHANGE,
    sector: 'Financials',
    isin: 'TRAGARAN91N1',
    active: true,
    providers: {
      yahoo: is('GARAN'),
      fintables: 'GARAN',
      kap: 'GARAN',
      tcmb: 'GARAN',
      mkk: 'GARAN',
    },
  },
  {
    canonicalTicker: 'ISCTR',
    companyName: 'Türkiye İş Bankası C',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAISCTR91N1',
    active: true,
    providers: {
      yahoo: is('ISCTR'),
      fintables: 'ISCTR',
      kap: 'ISCTR',
      tcmb: 'ISCTR',
      mkk: 'ISCTR',
    },
  },
  {
    canonicalTicker: 'YKBNK',
    companyName: 'Yapı Kredi Bankası',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAYKBNK91N7',
    active: true,
    providers: {
      yahoo: is('YKBNK'),
      fintables: 'YKBNK',
      kap: 'YKBNK',
      tcmb: 'YKBNK',
      mkk: 'YKBNK',
    },
  },
  {
    canonicalTicker: 'HALKB',
    companyName: 'Türkiye Halk Bankası',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAHALKB91H1',
    active: true,
    providers: {
      yahoo: is('HALKB'),
      fintables: 'HALKB',
      kap: 'HALKB',
      tcmb: 'HALKB',
      mkk: 'HALKB',
    },
  },
  {
    canonicalTicker: 'VAKBN',
    companyName: 'Türkiye Vakıflar Bankası',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAVAKBN91M7',
    active: true,
    providers: {
      yahoo: is('VAKBN'),
      fintables: 'VAKBN',
      kap: 'VAKBN',
      tcmb: 'VAKBN',
      mkk: 'VAKBN',
    },
  },
  {
    canonicalTicker: 'TSKB',
    companyName: 'Türkiye Sınai Kalkınma Bankası',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRATSKB91N6',
    active: true,
    providers: { yahoo: is('TSKB'), fintables: 'TSKB', kap: 'TSKB', tcmb: 'TSKB', mkk: 'TSKB' },
  },
  {
    canonicalTicker: 'SKBNK',
    companyName: 'Şekerbank',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRASKBNK91N8',
    active: true,
    providers: {
      yahoo: is('SKBNK'),
      fintables: 'SKBNK',
      kap: 'SKBNK',
      tcmb: 'SKBNK',
      mkk: 'SKBNK',
    },
  },
  {
    canonicalTicker: 'ALBRK',
    companyName: 'Albaraka Türk Katılım Bankası',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TREALBK00011',
    active: true,
    providers: {
      yahoo: is('ALBRK'),
      fintables: 'ALBRK',
      kap: 'ALBRK',
      tcmb: 'ALBRK',
      mkk: 'ALBRK',
    },
  },
  {
    canonicalTicker: 'ISMEN',
    companyName: 'İş Yatırım Menkul Değerler',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('ISMEN'),
      fintables: 'ISMEN',
      kap: 'ISMEN',
      tcmb: 'ISMEN',
      mkk: 'ISMEN',
    },
  },
  {
    canonicalTicker: 'KCHOL',
    companyName: 'Koç Holding',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAKCHOL91Q8',
    active: true,
    providers: {
      yahoo: is('KCHOL'),
      fintables: 'KCHOL',
      kap: 'KCHOL',
      tcmb: 'KCHOL',
      mkk: 'KCHOL',
    },
  },
  {
    canonicalTicker: 'SAHOL',
    companyName: 'Sabancı Holding',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: 'TRASAHOL91Q5',
    active: true,
    providers: {
      yahoo: is('SAHOL'),
      fintables: 'SAHOL',
      kap: 'SAHOL',
      tcmb: 'SAHOL',
      mkk: 'SAHOL',
    },
  },
  {
    canonicalTicker: 'ALARK',
    companyName: 'Alarko Holding',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAALARK91Q0',
    active: true,
    providers: {
      yahoo: is('ALARK'),
      fintables: 'ALARK',
      kap: 'ALARK',
      tcmb: 'ALARK',
      mkk: 'ALARK',
    },
  },
  {
    canonicalTicker: 'BRLSM',
    companyName: 'Borusan Yatırım ve Pazarlama',
    sector: 'Financials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('BRLSM'),
      fintables: 'BRLSM',
      kap: 'BRLSM',
      tcmb: 'BRLSM',
      mkk: 'BRLSM',
    },
  },
  {
    canonicalTicker: 'THYAO',
    companyName: 'Türk Hava Yolları',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRATHYAO91M5',
    active: true,
    providers: {
      yahoo: is('THYAO'),
      fintables: 'THYAO',
      kap: 'THYAO',
      tcmb: 'THYAO',
      mkk: 'THYAO',
    },
  },
  {
    canonicalTicker: 'PGSUS',
    companyName: 'Pegasus Hava Taşımacılığı',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAPGSUS91Q0',
    active: true,
    providers: {
      yahoo: is('PGSUS'),
      fintables: 'PGSUS',
      kap: 'PGSUS',
      tcmb: 'PGSUS',
      mkk: 'PGSUS',
    },
  },
  {
    canonicalTicker: 'CLEBI',
    companyName: 'Çelebi Hava Servisi',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRACLEBI91M5',
    active: true,
    providers: {
      yahoo: is('CLEBI'),
      fintables: 'CLEBI',
      kap: 'CLEBI',
      tcmb: 'CLEBI',
      mkk: 'CLEBI',
    },
  },
  {
    canonicalTicker: 'TAVHL',
    companyName: 'TAV Havalimanları Holding',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRETAVH00018',
    active: true,
    providers: {
      yahoo: is('TAVHL'),
      fintables: 'TAVHL',
      kap: 'TAVHL',
      tcmb: 'TAVHL',
      mkk: 'TAVHL',
    },
  },
  {
    canonicalTicker: 'TKFEN',
    companyName: 'Tekfen Holding',
    sector: 'Industrials',
    exchange: BIST_EXCHANGE,
    isin: 'TRETKHO00012',
    active: true,
    providers: {
      yahoo: is('TKFEN'),
      fintables: 'TKFEN',
      kap: 'TKFEN',
      tcmb: 'TKFEN',
      mkk: 'TKFEN',
    },
  },
  {
    canonicalTicker: 'BRSAN',
    companyName: 'Borusan Mannesmann',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('BRSAN'),
      fintables: 'BRSAN',
      kap: 'BRSAN',
      tcmb: 'BRSAN',
      mkk: 'BRSAN',
    },
  },
  {
    canonicalTicker: 'EREGL',
    companyName: 'Ereğli Demir ve Çelik',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAEREGL91Q3',
    active: true,
    providers: {
      yahoo: is('EREGL'),
      fintables: 'EREGL',
      kap: 'EREGL',
      tcmb: 'EREGL',
      mkk: 'EREGL',
    },
  },
  {
    canonicalTicker: 'KRDMD',
    companyName: 'Kardemir D',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('KRDMD'),
      fintables: 'KRDMD',
      kap: 'KRDMD',
      tcmb: 'KRDMD',
      mkk: 'KRDMD',
    },
  },
  {
    canonicalTicker: 'SISE',
    companyName: 'Şişecam',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRASISE91Q9',
    active: true,
    providers: { yahoo: is('SISE'), fintables: 'SISE', kap: 'SISE', tcmb: 'SISE', mkk: 'SISE' },
  },
  {
    canonicalTicker: 'SASA',
    companyName: 'SASA Polyester Sanayi',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: { yahoo: is('SASA'), fintables: 'SASA', kap: 'SASA', tcmb: 'SASA', mkk: 'SASA' },
  },
  {
    canonicalTicker: 'PETKM',
    companyName: 'Petkim Petrokimya',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAPETKM91Q7',
    active: true,
    providers: {
      yahoo: is('PETKM'),
      fintables: 'PETKM',
      kap: 'PETKM',
      tcmb: 'PETKM',
      mkk: 'PETKM',
    },
  },
  {
    canonicalTicker: 'KOZAL',
    companyName: 'Koza Altın İşletmeleri',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAKOZAL91P6',
    active: true,
    providers: {
      yahoo: is('KOZAL'),
      fintables: 'KOZAL',
      kap: 'KOZAL',
      tcmb: 'KOZAL',
      mkk: 'KOZAL',
    },
  },
  {
    canonicalTicker: 'KOZAA',
    companyName: 'Koza Anadolu Metal',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TREKOZA00014',
    active: true,
    providers: {
      yahoo: is('KOZAA'),
      fintables: 'KOZAA',
      kap: 'KOZAA',
      tcmb: 'KOZAA',
      mkk: 'KOZAA',
    },
  },
  {
    canonicalTicker: 'GUBRF',
    companyName: 'Gübre Fabrikaları',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAGUBRF91Q7',
    active: true,
    providers: {
      yahoo: is('GUBRF'),
      fintables: 'GUBRF',
      kap: 'GUBRF',
      tcmb: 'GUBRF',
      mkk: 'GUBRF',
    },
  },
  {
    canonicalTicker: 'HEKTS',
    companyName: 'Hektaş Ticaret',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAHEKTS91Q6',
    active: true,
    providers: {
      yahoo: is('HEKTS'),
      fintables: 'HEKTS',
      kap: 'HEKTS',
      tcmb: 'HEKTS',
      mkk: 'HEKTS',
    },
  },
  {
    canonicalTicker: 'AKSA',
    companyName: 'Aksa Akrilik Kimya',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: 'TRAAKSAW91E1',
    active: true,
    providers: { yahoo: is('AKSA'), fintables: 'AKSA', kap: 'AKSA', tcmb: 'AKSA', mkk: 'AKSA' },
  },
  {
    canonicalTicker: 'TUPRS',
    companyName: 'Tüpraş',
    sector: 'Energy',
    exchange: BIST_EXCHANGE,
    isin: 'TRATUPRS91Q8',
    active: true,
    providers: {
      yahoo: is('TUPRS'),
      fintables: 'TUPRS',
      kap: 'TUPRS',
      tcmb: 'TUPRS',
      mkk: 'TUPRS',
    },
  },
  {
    canonicalTicker: 'BIMAS',
    companyName: 'BİM Birleşik Mağazalar',
    sector: 'Consumer Staples',
    exchange: BIST_EXCHANGE,
    isin: 'TREBIMM00018',
    active: true,
    providers: {
      yahoo: is('BIMAS'),
      fintables: 'BIMAS',
      kap: 'BIMAS',
      tcmb: 'BIMAS',
      mkk: 'BIMAS',
    },
  },
  {
    canonicalTicker: 'MGROS',
    companyName: 'Migros Ticaret',
    sector: 'Consumer Staples',
    exchange: BIST_EXCHANGE,
    isin: 'TREMGRO00011',
    active: true,
    providers: {
      yahoo: is('MGROS'),
      fintables: 'MGROS',
      kap: 'MGROS',
      tcmb: 'MGROS',
      mkk: 'MGROS',
    },
  },
  {
    canonicalTicker: 'BIZIM',
    companyName: 'Bizim Toptan Satış',
    sector: 'Consumer Staples',
    exchange: BIST_EXCHANGE,
    isin: 'TREBIZIM00013',
    active: true,
    providers: {
      yahoo: is('BIZIM'),
      fintables: 'BIZIM',
      kap: 'BIZIM',
      tcmb: 'BIZIM',
      mkk: 'BIZIM',
    },
  },
  {
    canonicalTicker: 'SOKM',
    companyName: 'Şok Marketler',
    sector: 'Consumer Staples',
    exchange: BIST_EXCHANGE,
    isin: 'TRESOKM00022',
    active: true,
    providers: { yahoo: is('SOKM'), fintables: 'SOKM', kap: 'SOKM', tcmb: 'SOKM', mkk: 'SOKM' },
  },
  {
    canonicalTicker: 'DOAS',
    companyName: 'Doğuş Otomotiv',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRADOAS91R9',
    active: true,
    providers: { yahoo: is('DOAS'), fintables: 'DOAS', kap: 'DOAS', tcmb: 'DOAS', mkk: 'DOAS' },
  },
  {
    canonicalTicker: 'TOASO',
    companyName: 'Tofaş Otomobil Fabrikası',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRATOASO91Q3',
    active: true,
    providers: {
      yahoo: is('TOASO'),
      fintables: 'TOASO',
      kap: 'TOASO',
      tcmb: 'TOASO',
      mkk: 'TOASO',
    },
  },
  {
    canonicalTicker: 'FROTO',
    companyName: 'Ford Otomotiv Sanayi',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRAFROTO91Q4',
    active: true,
    providers: {
      yahoo: is('FROTO'),
      fintables: 'FROTO',
      kap: 'FROTO',
      tcmb: 'FROTO',
      mkk: 'FROTO',
    },
  },
  {
    canonicalTicker: 'OTKAR',
    companyName: 'Otokar Otomotiv',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRAOTKAR91Q2',
    active: true,
    providers: {
      yahoo: is('OTKAR'),
      fintables: 'OTKAR',
      kap: 'OTKAR',
      tcmb: 'OTKAR',
      mkk: 'OTKAR',
    },
  },
  {
    canonicalTicker: 'TTRAK',
    companyName: 'Türk Traktör',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRATTRAK91M5',
    active: true,
    providers: {
      yahoo: is('TTRAK'),
      fintables: 'TTRAK',
      kap: 'TTRAK',
      tcmb: 'TTRAK',
      mkk: 'TTRAK',
    },
  },
  {
    canonicalTicker: 'TRAK',
    companyName: 'Trakya Cam Sanayii',
    sector: 'Materials',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: false,
    delistedAt: '2023-05-02',
    providers: { yahoo: is('TRAK'), fintables: 'TRAK', kap: 'TRAK', tcmb: 'TRAK', mkk: 'TRAK' },
  },
  {
    canonicalTicker: 'VESTL',
    companyName: 'Vestel Elektronik',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRAVESTL91M4',
    active: true,
    providers: {
      yahoo: is('VESTL'),
      fintables: 'VESTL',
      kap: 'VESTL',
      tcmb: 'VESTL',
      mkk: 'VESTL',
    },
  },
  {
    canonicalTicker: 'ARCLK',
    companyName: 'Arçelik',
    sector: 'Consumer Discretionary',
    exchange: BIST_EXCHANGE,
    isin: 'TRAARCLK91H1',
    active: true,
    providers: {
      yahoo: is('ARCLK'),
      fintables: 'ARCLK',
      kap: 'ARCLK',
      tcmb: 'ARCLK',
      mkk: 'ARCLK',
    },
  },
  {
    canonicalTicker: 'TTKOM',
    companyName: 'Türk Telekomünikasyon',
    sector: 'Communication Services',
    exchange: BIST_EXCHANGE,
    isin: 'TRATTKOM91T5',
    active: true,
    providers: {
      yahoo: is('TTKOM'),
      fintables: 'TTKOM',
      kap: 'TTKOM',
      tcmb: 'TTKOM',
      mkk: 'TTKOM',
    },
  },
  {
    canonicalTicker: 'TCELL',
    companyName: 'Turkcell İletişim Hizmetleri',
    sector: 'Communication Services',
    exchange: BIST_EXCHANGE,
    isin: 'TRATCELL91Q1',
    active: true,
    providers: {
      yahoo: is('TCELL'),
      fintables: 'TCELL',
      kap: 'TCELL',
      tcmb: 'TCELL',
      mkk: 'TCELL',
    },
  },
  {
    canonicalTicker: 'ASELS',
    companyName: 'ASELSAN',
    sector: 'Information Technology',
    exchange: BIST_EXCHANGE,
    isin: 'TRAASELS91Q1',
    active: true,
    providers: {
      yahoo: is('ASELS'),
      fintables: 'ASELS',
      kap: 'ASELS',
      tcmb: 'ASELS',
      mkk: 'ASELS',
    },
  },
  {
    canonicalTicker: 'KONTR',
    companyName: 'Kontrolmatik Teknoloji',
    sector: 'Information Technology',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('KONTR'),
      fintables: 'KONTR',
      kap: 'KONTR',
      tcmb: 'KONTR',
      mkk: 'KONTR',
    },
  },
  {
    canonicalTicker: 'EKGYO',
    companyName: 'Emlak Konut Gayrimenkul Yatırım Ortaklığı',
    sector: 'Real Estate',
    exchange: BIST_EXCHANGE,
    isin: 'TRAGEKGY91Q0',
    active: true,
    providers: {
      yahoo: is('EKGYO'),
      fintables: 'EKGYO',
      kap: 'EKGYO',
      tcmb: 'EKGYO',
      mkk: 'EKGYO',
    },
  },
  {
    canonicalTicker: 'ZOREN',
    companyName: 'Zorlu Enerji Elektrik Üretim',
    sector: 'Utilities',
    exchange: BIST_EXCHANGE,
    isin: 'TRAZOREN91T3',
    active: true,
    providers: {
      yahoo: is('ZOREN'),
      fintables: 'ZOREN',
      kap: 'ZOREN',
      tcmb: 'ZOREN',
      mkk: 'ZOREN',
    },
  },
  {
    canonicalTicker: 'TRCAS',
    companyName: 'Türkiye Şeker Fabrikaları',
    sector: 'Utilities',
    exchange: BIST_EXCHANGE,
    isin: null,
    active: true,
    providers: {
      yahoo: is('TRCAS'),
      fintables: 'TRCAS',
      kap: 'TRCAS',
      tcmb: 'TRCAS',
      mkk: 'TRCAS',
    },
  },
  {
    canonicalTicker: 'ENJSA',
    companyName: 'Enerjisa Enerji',
    sector: 'Utilities',
    exchange: BIST_EXCHANGE,
    isin: 'TREENSA00014',
    active: true,
    providers: {
      yahoo: is('ENJSA'),
      fintables: 'ENJSA',
      kap: 'ENJSA',
      tcmb: 'ENJSA',
      mkk: 'ENJSA',
    },
  },
  {
    canonicalTicker: 'ODAS',
    companyName: 'Odaş Elektrik Üretim',
    sector: 'Utilities',
    exchange: BIST_EXCHANGE,
    isin: 'TRAODAS91Q4',
    active: true,
    providers: { yahoo: is('ODAS'), fintables: 'ODAS', kap: 'ODAS', tcmb: 'ODAS', mkk: 'ODAS' },
  },
];

export const BIST_SYMBOL_MAP: Map<string, BistSymbolEntry> = new Map(
  BIST_SYMBOLS.map((entry) => [entry.canonicalTicker, entry]),
);

export const BIST_ACTIVE_SYMBOLS: string[] = BIST_SYMBOLS.filter((entry) => entry.active).map(
  (entry) => entry.canonicalTicker,
);
