import type { SDKGeneratorConfig } from './sdk-generator.types';

export const DEFAULT_SDK_CONFIG: SDKGeneratorConfig = {
  outputDir: 'generated-sdk',
  clientClassName: 'BistEliteClient',
  clientFileName: 'client.ts',
  typesDir: 'types',
  enumsDir: 'enums',
  modulesDir: 'modules',
  enablePagination: true,
  enableRetry: true,
  maxRetries: 3,
  retryDelayMs: 1000,
  enableInterceptors: true,
  indentSize: 2,
  exportBanner: '/* Auto-generated by SDK Generator — DO NOT EDIT */',
  generateReadme: false,
};

export const RESERVED_KEYWORDS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default',
  'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally',
  'for', 'function', 'if', 'import', 'in', 'instanceof', 'new', 'null',
  'return', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof',
  'var', 'void', 'while', 'with', 'yield', 'let', 'static', 'async',
  'await', 'implements', 'interface', 'package', 'private', 'protected',
  'public', 'abstract', 'boolean', 'byte', 'char', 'double', 'final',
  'float', 'goto', 'int', 'long', 'native', 'short', 'synchronized',
  'transient', 'volatile', 'undefined', 'NaN', 'Infinity', 'require',
  'console', 'process', 'global', 'globalThis', 'document', 'window',
]);

export const TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'number',
  integer: 'number',
  boolean: 'boolean',
  object: 'Record<string, unknown>',
  array: 'unknown[]',
};

export const PAGINATION_OPS = new Set([
  'getTopCandidates',
  'getWatchlist',
  'getRejected',
  'getQueueJobs',
  'getEvents',
  'getEventsByType',
  'getProviderHistory',
  'getConfigHistory',
  'getJobHistory',
  'getNotifications',
  'getTimeline',
]);
