import type { ValidationConfig, ValidationCategory } from './contract-validator.types';

export const DEFAULT_VALIDATION_CONFIG: ValidationConfig = {
  strictMode: false,
  checkBreakingChanges: true,
  checkNullability: true,
  checkOptionality: true,
  checkPagination: true,
  checkVersionCompatibility: true,
  checkSDKConsistency: true,
  schemaCacheEnabled: true,
  sdkCacheEnabled: true,
  maxSchemaCacheSize: 1000,
  maxSDKCacheSize: 100,
  reportFormat: 'json',
  exportBanner: '/* Auto-generated by Contract Validator — DO NOT EDIT */',
  indentSize: 2,
};

export const ALL_VALIDATION_CATEGORIES: ValidationCategory[] = [
  'SCHEMA_CONSISTENCY',
  'DTO_COMPATIBILITY',
  'ENUM_COMPATIBILITY',
  'ENDPOINT_COMPATIBILITY',
  'TYPE_COMPATIBILITY',
  'PAGINATION_COMPATIBILITY',
  'NULLABLE_COMPATIBILITY',
  'OPTIONAL_COMPATIBILITY',
  'VERSION_COMPATIBILITY',
  'SDK_COMPATIBILITY',
  'BREAKING_CHANGE',
];

export const SCHEMA_TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'number',
  integer: 'number',
  boolean: 'boolean',
  object: 'Record<string, unknown>',
  array: 'unknown[]',
  null: 'null',
};

export const REQUIRED_SCHEMA_PROPERTIES = [
  'type',
  'properties',
  'required',
  'items',
  'enum',
  '$ref',
  'allOf',
  'oneOf',
] as const;

export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;

export const BREAKING_CHANGE_PATTERNS = [
  { pattern: /removed required property/i, impact: 'HIGH' as const },
  { pattern: /removed endpoint/i, impact: 'HIGH' as const },
  { pattern: /changed endpoint method/i, impact: 'HIGH' as const },
  { pattern: /removed enum value/i, impact: 'MEDIUM' as const },
  { pattern: /changed parameter.*required/i, impact: 'MEDIUM' as const },
  { pattern: /changed response type/i, impact: 'MEDIUM' as const },
  { pattern: /removed optional property/i, impact: 'LOW' as const },
  { pattern: /added required parameter/i, impact: 'MEDIUM' as const },
  { pattern: /changed pagination/i, impact: 'LOW' as const },
];

export const VERSION_COMPATIBILITY_RULES = {
  majorVersionChange: 'BREAKING' as const,
  minorVersionChange: 'COMPATIBLE' as const,
  patchVersionChange: 'COMPATIBLE' as const,
};

export const PAGINATION_FIELDS = ['offset', 'limit', 'page', 'pageSize', 'total', 'count'] as const;
